# Generated by Django 6.0.6 on 2026-06-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.IntegerField(choices=[(1, 'پایین'), (2, 'متوسط'), (3, 'بالا')], default=2),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('in_progress', 'در حال انجام'), ('done', 'انجام شده')], default='pending', max_length=20),
        ),
    ]
